version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - .db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
