"""empty message

Revision ID: 0d2ff1c5b138
Revises: d849e5321a76
Create Date: 2021-11-29 16:14:54.791081

"""
from alembic import op
import sqlalchemy as sa


revision = '0d2ff1c5b138'
down_revision = 'd849e5321a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
