"""empty message

Revision ID: 11f1492db3b8
Revises: 
Create Date: 2021-11-05 20:23:01.256748

"""
from alembic import op
import sqlalchemy as sa


revision = '11f1492db3b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rgb', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('part_url', sa.String(), nullable=True),
    sa.Column('part_img_url', sa.String(), nullable=True),
    sa.Column('id_bricklink', sa.String(), nullable=True),
    sa.Column('id_brickowl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('id_theme', sa.Integer(), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.Column('set_img_url', sa.String(), nullable=True),
    sa.Column('set_url', sa.String(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('parted_out_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_set', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_set'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_part', sa.String(), nullable=True),
    sa.Column('id_color', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=1), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id_parted_out_set', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_color'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['id_part'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['id_parted_out_set'], ['parted_out_sets.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_part', 'id_color', 'condition', 'id_parted_out_set', 'id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_parts')
    op.drop_table('parted_out_sets')
    op.drop_table('users')
    op.drop_table('sets')
    op.drop_table('parts')
    op.drop_table('colors')
    # ### end Alembic commands ###
