"""empty message

Revision ID: 1cb278706b8b
Revises: a555413424be
Create Date: 2021-11-15 08:59:55.710626

"""
from alembic import op
import sqlalchemy as sa


revision = '1cb278706b8b'
down_revision = 'a555413424be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
