"""empty message

Revision ID: 23d3a6243fcc
Revises: 08219f2436ba
Create Date: 2021-11-13 20:50:28.578000

"""
from alembic import op
import sqlalchemy as sa


revision = '23d3a6243fcc'
down_revision = '08219f2436ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('syncer_enable_timestmap', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('syncer_running', sa.Boolean(), nullable=True))
    op.alter_column('users', 'syncer_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'syncer_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'syncer_running')
    op.drop_column('users', 'syncer_enable_timestmap')
    # ### end Alembic commands ###
