"""empty message

Revision ID: 2ae911bb0b28
Revises: 7f08dc2361ba
Create Date: 2021-11-11 00:47:54.048878

"""
from alembic import op
import sqlalchemy as sa


revision = '2ae911bb0b28'
down_revision = '7f08dc2361ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('id_bo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'id_bo')
    # ### end Alembic commands ###
