"""empty message

Revision ID: 3d90bffa77db
Revises: 452ce0a01f88
Create Date: 2021-11-12 01:43:36.663663

"""
from alembic import op
import sqlalchemy as sa


revision = '3d90bffa77db'
down_revision = '452ce0a01f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bl_credentials_approved', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('bo_credentials_approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bo_credentials_approved')
    op.drop_column('users', 'bl_credentials_approved')
    # ### end Alembic commands ###
