"""empty message

Revision ID: 42fb82a7cbc4
Revises: 1e2360a68156
Create Date: 2021-11-28 21:31:46.389606

"""
from alembic import op
import sqlalchemy as sa


revision = '42fb82a7cbc4'
down_revision = '1e2360a68156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bl_credentials_approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('bo_credentials_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bo_credentials_approved')
    op.drop_column('users', 'bl_credentials_approved')
    # ### end Alembic commands ###
