"""empty message

Revision ID: 452ce0a01f88
Revises: 6014a738001c
Create Date: 2021-11-12 01:27:17.395566

"""
from alembic import op
import sqlalchemy as sa


revision = '452ce0a01f88'
down_revision = '6014a738001c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bl_customer_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bl_customer_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bl_token_value', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bl_token_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bo_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bo_key')
    op.drop_column('users', 'bl_token_secret')
    op.drop_column('users', 'bl_token_value')
    op.drop_column('users', 'bl_customer_secret')
    op.drop_column('users', 'bl_customer_key')
    # ### end Alembic commands ###
