"""Add prices to catalog items

Revision ID: 45d7582f22d3
Revises: 46fd0403655c
Create Date: 2023-01-23 13:35:48.026127

"""
from alembic import op
import sqlalchemy as sa


revision = '45d7582f22d3'
down_revision = '46fd0403655c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('new_min_price', sa.Numeric(), nullable=True))
    op.add_column('items', sa.Column('new_avg_price', sa.Numeric(), nullable=True))
    op.add_column('items', sa.Column('new_max_price', sa.Numeric(), nullable=True))
    op.add_column('items', sa.Column('new_price_updated_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('used_min_price', sa.Numeric(), nullable=True))
    op.add_column('items', sa.Column('used_avg_price', sa.Numeric(), nullable=True))
    op.add_column('items', sa.Column('used_max_price', sa.Numeric(), nullable=True))
    op.add_column('items', sa.Column('used_price_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'used_price_updated_at')
    op.drop_column('items', 'used_max_price')
    op.drop_column('items', 'used_avg_price')
    op.drop_column('items', 'used_min_price')
    op.drop_column('items', 'new_price_updated_at')
    op.drop_column('items', 'new_max_price')
    op.drop_column('items', 'new_avg_price')
    op.drop_column('items', 'new_min_price')
    # ### end Alembic commands ###
