"""Remove unique constriant on inventory_items (what if unit_price is different?)

Revision ID: 46fd0403655c
Revises: 3d66a171f46a
Create Date: 2023-01-19 18:56:11.015541

"""
from alembic import op
import sqlalchemy as sa


revision = '46fd0403655c'
down_revision = '3d66a171f46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_items_user_id_item_id_item_type_color_id_conditio_key', 'inventory_items', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('inventory_items_user_id_item_id_item_type_color_id_conditio_key', 'inventory_items', ['user_id', 'item_id', 'item_type', 'color_id', 'condition', 'user_remarks'])
    # ### end Alembic commands ###
