"""empty message

Revision ID: 4f29956cedce
Revises: 5e29b1d027c0
Create Date: 2021-11-22 15:07:06.906477

"""
from alembic import op
import sqlalchemy as sa


revision = '4f29956cedce'
down_revision = '5e29b1d027c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('op_view',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('op_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['op_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_group', 'when')
    )
    op.add_column('op', sa.Column('id_group', sa.Integer(), nullable=False))
    op.drop_constraint('op_id_parent_fkey', 'op', type_='foreignkey')
    op.drop_constraint('op_id_user_fkey', 'op', type_='foreignkey')
    op.create_foreign_key(None, 'op', 'op', ['id_parent'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'op', 'op_groups', ['id_group'], ['id'], ondelete='CASCADE')
    op.drop_column('op', 'id_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'op', type_='foreignkey')
    op.drop_constraint(None, 'op', type_='foreignkey')
    op.create_foreign_key('op_id_user_fkey', 'op', 'users', ['id_user'], ['id'])
    op.create_foreign_key('op_id_parent_fkey', 'op', 'op', ['id_parent'], ['id'])
    op.drop_column('op', 'id_group')
    op.drop_table('op_view')
    op.drop_table('op_groups')
    # ### end Alembic commands ###
