"""empty message

Revision ID: 5d16ed5d6f4e
Revises: f4186b271309
Create Date: 2021-11-29 14:56:06.635095

"""
from alembic import op
import sqlalchemy as sa


revision = '5d16ed5d6f4e'
down_revision = 'f4186b271309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('color_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_items_id_order_item_id_item_type_id_color_condition_q_key', 'order_items', type_='unique')
    op.create_unique_constraint(None, 'order_items', ['order_id', 'item_id', 'item_type', 'color_id', 'condition', 'quantity', 'user_remarks', 'user_description'])
    op.drop_constraint('order_items_id_color_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_id_order_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'colors', ['color_id'], ['id'])
    op.drop_column('order_items', 'id_color')
    op.drop_column('order_items', 'id_order')
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('bl_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('bo_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('applied', sa.Boolean(), nullable=True))
    op.drop_constraint('orders_id_user_buyer_name_buyer_email_date_ordered_key', 'orders', type_='unique')
    op.create_unique_constraint(None, 'orders', ['user_id', 'buyer_name', 'buyer_email', 'date_ordered'])
    op.drop_constraint('orders_id_user_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'id_bo')
    op.drop_column('orders', 'id_user')
    op.drop_column('orders', 'id_bl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('id_bl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('id_bo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_id_user_fkey', 'orders', 'users', ['id_user'], ['id'])
    op.drop_constraint(None, 'orders', type_='unique')
    op.create_unique_constraint('orders_id_user_buyer_name_buyer_email_date_ordered_key', 'orders', ['id_user', 'buyer_name', 'buyer_email', 'date_ordered'])
    op.drop_column('orders', 'applied')
    op.drop_column('orders', 'bo_id')
    op.drop_column('orders', 'bl_id')
    op.drop_column('orders', 'user_id')
    op.add_column('order_items', sa.Column('id_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('id_color', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_id_order_fkey', 'order_items', 'orders', ['id_order'], ['id'])
    op.create_foreign_key('order_items_id_color_fkey', 'order_items', 'colors', ['id_color'], ['id'])
    op.drop_constraint(None, 'order_items', type_='unique')
    op.create_unique_constraint('order_items_id_order_item_id_item_type_id_color_condition_q_key', 'order_items', ['id_order', 'item_id', 'item_type', 'id_color', 'condition', 'quantity', 'user_remarks', 'user_description'])
    op.drop_column('order_items', 'color_id')
    op.drop_column('order_items', 'order_id')
    # ### end Alembic commands ###
