"""empty message

Revision ID: 5e29b1d027c0
Revises: 811387f06e83
Create Date: 2021-11-15 12:06:28.178708

"""
from alembic import op
import sqlalchemy as sa


revision = '5e29b1d027c0'
down_revision = '811387f06e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_parts', sa.Column('unit_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_parts', 'unit_price')
    # ### end Alembic commands ###
