"""empty message

Revision ID: 6014a738001c
Revises: 
Create Date: 2021-11-11 23:56:07.109205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6014a738001c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rgb', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('id_bo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('bl_current_hour', sa.Integer(), nullable=True),
    sa.Column('bl_current_hour_requests_count', sa.Integer(), nullable=True),
    sa.Column('bl_api_current_day', sa.Integer(), nullable=True),
    sa.Column('bl_api_current_day_requests_count', sa.Integer(), nullable=True),
    sa.Column('bo_api_current_minute_requests_count', sa.Integer(), nullable=True),
    sa.Column('bo_api_current_minute', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('id_dependency', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_dependency'], ['op.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('buyer_email', sa.String(length=512), nullable=False),
    sa.Column('date_ordered', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'PENDING', 'PAID', 'PROCESSING', 'PROCESSED', 'SHIPPED', 'RECEIVED', name='orderstatus'), nullable=False),
    sa.Column('shipping_method', sa.String(), nullable=True),
    sa.Column('shipping_address_first_name', sa.String(), nullable=True),
    sa.Column('shipping_address_last_name', sa.String(), nullable=True),
    sa.Column('shipping_address_address_1', sa.String(), nullable=True),
    sa.Column('shipping_address_address_2', sa.String(), nullable=True),
    sa.Column('shipping_address_country_code', sa.String(), nullable=True),
    sa.Column('shipping_address_city', sa.String(), nullable=True),
    sa.Column('shipping_address_state', sa.String(), nullable=True),
    sa.Column('shipping_address_postal_code', sa.String(), nullable=True),
    sa.Column('id_bl', sa.Integer(), nullable=True),
    sa.Column('id_bo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'buyer_name', 'buyer_email', 'date_ordered')
    )
    op.create_table('parts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('id_bo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_part', sa.String(), nullable=False),
    sa.Column('id_color', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=1), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_remarks', sa.String(), nullable=True),
    sa.Column('user_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_color'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['id_part'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'id_part', 'id_color', 'condition', 'user_remarks')
    )
    op.create_table('order_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_part', sa.String(), nullable=False),
    sa.Column('id_color', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=1), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_remarks', sa.String(), nullable=True),
    sa.Column('user_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_color'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_part'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_order', 'id_part', 'id_color', 'condition', 'quantity', 'user_remarks', 'user_description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_parts')
    op.drop_table('inventory_parts')
    op.drop_table('sets')
    op.drop_table('parts')
    op.drop_table('orders')
    op.drop_table('op')
    op.drop_table('users')
    op.drop_table('colors')
    op.drop_table('categories')
    # ### end Alembic commands ###
