"""empty message

Revision ID: 7017f4f7e5b1
Revises: a618ea9772dc
Create Date: 2021-11-12 15:45:09.530900

"""
from alembic import op
import sqlalchemy as sa


revision = '7017f4f7e5b1'
down_revision = 'a618ea9772dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('syncer_enabled', sa.Boolean(), nullable=False))
    op.drop_column('users', 'bo_inventory_id')
    op.drop_column('users', 'bl_inventory_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bl_inventory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bo_inventory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'syncer_enabled')
    # ### end Alembic commands ###
