"""empty message

Revision ID: 75542b25251b
Revises: 23d3a6243fcc
Create Date: 2021-11-13 20:59:48.970701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '75542b25251b'
down_revision = '23d3a6243fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('syncer_enable_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('users', 'syncer_enable_timestmap')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('syncer_enable_timestmap', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'syncer_enable_timestamp')
    # ### end Alembic commands ###
