"""empty message

Revision ID: 756b5f61d1d4
Revises: 0d2ff1c5b138
Create Date: 2021-11-29 16:25:26.135857

"""
from alembic import op
import sqlalchemy as sa


revision = '756b5f61d1d4'
down_revision = '0d2ff1c5b138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
