"""empty message

Revision ID: 7f08dc2361ba
Revises: f2c9bf8798f0
Create Date: 2021-11-10 18:16:53.439989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7f08dc2361ba'
down_revision = 'f2c9bf8798f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('parts', 'img_url')
    op.add_column('users', sa.Column('bl_current_hour', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bl_current_hour_requests_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bl_api_current_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bl_api_current_day_requests_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bo_api_current_minute_requests_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bo_api_current_minute', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bo_api_current_minute')
    op.drop_column('users', 'bo_api_current_minute_requests_count')
    op.drop_column('users', 'bl_api_current_day_requests_count')
    op.drop_column('users', 'bl_api_current_day')
    op.drop_column('users', 'bl_current_hour_requests_count')
    op.drop_column('users', 'bl_current_hour')
    op.add_column('parts', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('op')
    # ### end Alembic commands ###
