"""empty message

Revision ID: 811387f06e83
Revises: 1cb278706b8b
Create Date: 2021-11-15 10:03:49.645032

"""
from alembic import op
import sqlalchemy as sa


revision = '811387f06e83'
down_revision = '1cb278706b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('rate_limited_at', sa.DateTime(), nullable=True))
    op.add_column('op', sa.Column('rate_limited_for', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'rate_limited_for')
    op.drop_column('op', 'rate_limited_at')
    # ### end Alembic commands ###
