"""empty message

Revision ID: 98d460f596d5
Revises: 11f1492db3b8
Create Date: 2021-11-06 19:01:27.786531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '98d460f596d5'
down_revision = '11f1492db3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colors', sa.Column('id_bricklink', sa.Integer(), nullable=True))
    op.add_column('colors', sa.Column('id_brickowl', sa.Integer(), nullable=True))
    op.alter_column('colors', 'rgb',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.drop_column('sets', 'last_modified_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('colors', 'rgb',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.drop_column('colors', 'id_brickowl')
    op.drop_column('colors', 'id_bricklink')
    # ### end Alembic commands ###
