"""empty message

Revision ID: 9aa7762bb8c3
Revises: d88d13b545f9
Create Date: 2021-11-29 16:28:23.878532

"""
from alembic import op
import sqlalchemy as sa


revision = '9aa7762bb8c3'
down_revision = 'd88d13b545f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'PACKED', 'SHIPPED', 'RECEIVED', 'ON_HOLD', 'CANCELLED', 'PURGED', 'UNKNOWN', name='orderstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
