"""empty message

Revision ID: a618ea9772dc
Revises: 3d90bffa77db
Create Date: 2021-11-12 15:10:21.136210

"""
from alembic import op
import sqlalchemy as sa


revision = 'a618ea9772dc'
down_revision = '3d90bffa77db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bl_inventory_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bo_inventory_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bo_inventory_id')
    op.drop_column('users', 'bl_inventory_id')
    # ### end Alembic commands ###
