"""empty message

Revision ID: c6628856b478
Revises: 52434e15a484
Create Date: 2021-11-07 23:44:09.057323

"""
from alembic import op
import sqlalchemy as sa


revision = 'c6628856b478'
down_revision = '52434e15a484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('id_bricklink', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('id_brickowl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'id_brickowl')
    op.drop_column('orders', 'id_bricklink')
    # ### end Alembic commands ###
