"""empty message

Revision ID: d849e5321a76
Revises: fc1cb9d9e0e0
Create Date: 2021-11-29 16:00:11.970063

"""
from alembic import op
import sqlalchemy as sa


revision = 'd849e5321a76'
down_revision = 'fc1cb9d9e0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('image_pulled', sa.Integer(), nullable=True))
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_column('order_items', 'image_pulled')
    # ### end Alembic commands ###
