"""empty message

Revision ID: d88d13b545f9
Revises: 756b5f61d1d4
Create Date: 2021-11-29 16:28:13.414893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd88d13b545f9'
down_revision = '756b5f61d1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', postgresql.ENUM('UNKNOWN', 'PENDING', 'PAID', 'PROCESSING', 'PROCESSED', 'SHIPPED', 'RECEIVED', name='orderstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
