"""empty message

Revision ID: dd65c3468b56
Revises: 4f29956cedce
Create Date: 2021-11-23 21:05:26.219543

"""
from alembic import op
import sqlalchemy as sa


revision = 'dd65c3468b56'
down_revision = '4f29956cedce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('op_dependencies_id_op_fkey', 'op_dependencies', type_='foreignkey')
    op.drop_constraint('op_dependencies_id_dependency_fkey', 'op_dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'op_dependencies', 'op', ['id_dependency'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'op_dependencies', 'op', ['id_op'], ['id'], ondelete='CASCADE')
    op.add_column('op_groups', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op_groups', 'processed_at')
    op.drop_constraint(None, 'op_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'op_dependencies', type_='foreignkey')
    op.create_foreign_key('op_dependencies_id_dependency_fkey', 'op_dependencies', 'op', ['id_dependency'], ['id'])
    op.create_foreign_key('op_dependencies_id_op_fkey', 'op_dependencies', 'op', ['id_op'], ['id'])
    # ### end Alembic commands ###
