"""Use separate item_prices table

Revision ID: ef9107e3afae
Revises: 45d7582f22d3
Create Date: 2023-01-23 13:49:22.924420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ef9107e3afae'
down_revision = '45d7582f22d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_prices',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('min_price', sa.Numeric(), nullable=True),
    sa.Column('avg_price', sa.Numeric(), nullable=True),
    sa.Column('max_price', sa.Numeric(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id', 'item_type', 'color_id', 'condition')
    )
    op.drop_column('items', 'used_avg_price')
    op.drop_column('items', 'new_max_price')
    op.drop_column('items', 'new_avg_price')
    op.drop_column('items', 'new_min_price')
    op.drop_column('items', 'used_min_price')
    op.drop_column('items', 'new_price_updated_at')
    op.drop_column('items', 'used_price_updated_at')
    op.drop_column('items', 'used_max_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('used_max_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('used_price_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('new_price_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('used_min_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('new_min_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('new_avg_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('new_max_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('used_avg_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_table('item_prices')
    # ### end Alembic commands ###
