"""empty message

Revision ID: f2c9bf8798f0
Revises: c6628856b478
Create Date: 2021-11-08 19:53:03.053431

"""
from alembic import op
import sqlalchemy as sa


revision = 'f2c9bf8798f0'
down_revision = 'c6628856b478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bo_colors',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id_bricklink', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_bricklink'], ['colors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'applied_orders', ['id_order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applied_orders', type_='unique')
    op.drop_table('bo_colors')
    # ### end Alembic commands ###
