"""empty message

Revision ID: f2ee932fc2ff
Revises: 6fee37cde4a3
Create Date: 2021-11-24 15:42:11.773164

"""
from alembic import op
import sqlalchemy as sa


revision = 'f2ee932fc2ff'
down_revision = '6fee37cde4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('op', 'id_group',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('op', 'id_group',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
