"""empty message

Revision ID: fc1cb9d9e0e0
Revises: 5d16ed5d6f4e
Create Date: 2021-11-29 15:00:55.568911

"""
from alembic import op
import sqlalchemy as sa


revision = 'fc1cb9d9e0e0'
down_revision = '5d16ed5d6f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
